# Paths & Directories
music_directory                     "~/Music"
follow_outside_symlinks             "yes"
follow_inside_symlinks              "yes"

playlist_directory                  "~/Music/playlists"
db_file			                        "$XDG_CACHE_HOME/mpd/database"
pid_file			                      "$XDG_RUNTIME_DIR/mpd/mpd.pid"
state_file			                    "$XDG_RUNTIME_DIR/mpd/state"
sticker_file                        "$XDG_CACHE_HOME/mpd/sticker.sql"

# Performance & Automation
auto_update                         "yes"
save_absolute_paths_in_playlists    "no"

# Connections & Network Security
bind_to_address                     "127.0.0.1"
bind_to_address                     "~/.config/mpd/socket"
port                                "6600"

# Audio Settings
replaygain                          "auto"

# Network Streaming Engine
input {
    plugin "curl"
}

# Audio Routing
audio_output {
    type                            "pipewire"
    name                            "PipeWire Sound Server"
}

