format = """
[](#9A348E)\
$os\
${custom.homename}\
${custom.username}\
[](bg:#00ffffff fg:#9A348E)\
[](bg:#DA627D fg:#000000)\
${custom.dir}\
${custom.home_dir}\
$directory\
[](fg:#DA627D bg:#fffb38)\
${custom.giturl}\
$git_branch\
$git_status\
[](fg:#fffb38 bg:#5FAFFF)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#5FAFFF bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#6CA35E)\
$time\
[](fg:#6CA35E)\
$character"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below

[custom.homename]
command = "echo collins "
when = '[ "$PWD" == "$HOME" ]'
shell = ["bash","--norc","--noprofile"]
style = "bg:#9A348E white bold"
format = "[$output ]($style)"

[custom.username]
command = "echo ck "
when = '[ "$PWD" != "$HOME" ]'
shell = ["bash","--norc","--noprofile"]
style = "bg:#9A348E white bold"
format = "[$output ]($style)"

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "bg:#DA627D white bold"
read_only = " "
format = "[ $path ]($style)"
truncation_length = 3
#truncation_symbol = "…/"

[custom.home_dir]
command = "echo  "
when = '[ "$PWD" == "$HOME" ]'
shell = ["bash","--norc","--noprofile"]
style = "bg:#DA627D white bold"
format = "[ $output]($style)"

[custom.dir]
command = "echo  "
when = '[ "$PWD" != "$HOME" ]'
shell = ["bash","--norc","--noprofile"]
style = "bg:#DA627D white bold"
format = "[ $output]($style)"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:

[character]
success_symbol = "[ ](#ffffff)"
error_symbol = "[  ](red)"
vicmd_symbol = "[  ](purple)"


[custom.end]
format = "[ ](bg:#06969A)"

[custom.giturl]
# disabled = true
description = "Display symbol for remote Git server"
shell = ["bash", "--noprofile", "--norc"]
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL=" "
else
    GIT_REMOTE_SYMBOL=" "
fi
echo "$GIT_REMOTE_SYMBOL "
"""
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
style = "bg:#fffb38 black"
format = "[ $output ]($style)"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#5FAFFF #ffffff"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#5FAFFF #ffffff"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#5FAFFF #ffffff"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#fffb38 black"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#fffb38 black"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#5FAFFF #ffffff"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#5FAFFF #ffffff"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#5FAFFF #ffffff"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#5FAFFF #ffffff"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#5FAFFF #ffffff"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#5FAFFF #000000"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#5FAFFF #ffffff"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#5FAFFF #ffffff"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#5FAFFF #ffffff"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#6CA35E #ffffff"
format = '[ $time ]($style)'

