hl.env("QT_QPA_PLATFORMTHEME", "qt5ct;kde")
hl.env("QT_STYLE_OVERRIDE", "kvantum")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("_JAVA_OPTIONS", "-Dawt.useSystemAAFontSettings=lcd -Dswing.aatext=true")
