# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# lua require('base46').toggle_transparency()

# windowrule = opacity 0.8 0.8, class:kitty
# windowrule = opacity 0.9 0.9, class:foot
# windowrule = opacity 0.7 0.7, class:nautilus
# windowrule = opacity 0.7 0.7, class:foot
windowrule = match:class cheatsheet, match:title neutrino, float true, size 900 600, center true, border_size 2

# New updated windowrule syntax for Hyprland 0.54
windowrule = match:class ^(org.kde.dolphin)$, opacity 0.90 0.90
windowrule = match:class ^(org.gnome.Nautilus)$, opacity 0.90 0.90
windowrule = match:class ^(thunar)$, opacity 0.90 0.90
windowrule = match:class ^(brave)$|^(brave-browser)$, opacity 0.95 0.95 override
windowrule = match:class ^(obsidian)$, opacity 0.95 0.95
windowrule = match:class ^(rofi)$, opacity 0.90 0.90


